spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_cloud?autoReconnect=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8070
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/